export const ADD_COIN = 'ADD_COIN'

/* AUTHENTICATION */
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCCESS = 'AUTH_GET_STATUS_SUCCESS';
export const AUTH_GET_STATUS_FAILURE = 'AUTH_GET_STATUS_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

/* COINS */
export const COIN_LIST = 'COIN_LIST';
export const COIN_LIST_SUCCESS = 'COIN_LIST_SUCCESS';
export const COIN_LIST_FAILURE = 'COIN_LIST_FAILURE';

export const COIN_REGISTER = 'COIN_REGISTER';
export const COIN_REGISTER_SUCCESS = 'COIN_REGISTER_SUCCESS';
export const COIN_REGISTER_FAILURE = 'COIN_REGISTER_FAILURE';

export const COIN_REMOVE = 'COIN_REMOVE';
export const COIN_REMOVE_SUCCESS = 'COIN_REMOVE_SUCCESS';
export const COIN_REMOVE_FAILURE = 'COIN_REMOVE_FAILURE';
